id: P004494
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016686
  title: ཁམས་སྒོམ་སྡེ་ནང་ཆེན་པའི་དགོན་ཁག་རྣམས་ཀྱི་བྱུང་བ་ཕྱོགས་བསྒྲིགས་རིན་ཆེན་སྒྲོམ་བརྒྱ་འབྱེད་པའི་དེབ་ཐེར་གསེར་གྱི་ལྡེ་མིག
  author: ''
  volumes: {}
