id: P004494
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:26:47.729398
source_metadata:
  id: bdr:W00EGS1016686
  title: ཁམས་སྒོམ་སྡེ་ནང་ཆེན་པའི་དགོན་ཁག་རྣམས་ཀྱི་བྱུང་བ་ཕྱོགས་བསྒྲིགས་རིན་ཆེན་སྒྲོམ་བརྒྱ་འབྱེད་པའི་དེབ་ཐེར་གསེར་གྱི་ལྡེ་མིག
  author: ''
  volumes:
    8e1fcfe9178e4c86961481cfc8317b30:
      image_group_id: I01JW127
      title: ''
      volume_number: 1
      total_pages: 725
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
