id: ID64CC7E7
legacy_id: P004494
ocr_import_info:
  bdrc_scan_id: W00EGS1016686
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T06:38:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T03:19:02.710602+00:00'
last_modified: 2022-08-27 11:21:23.547780
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016686
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016686
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁམས་སྒོམ་སྡེ་ནང་ཆེན་པའི་དགོན་ཁག་རྣམས་ཀྱི་བྱུང་བ་ཕྱོགས་བསྒྲིགས་རིན་ཆེན་སྒྲོམ་བརྒྱ་འབྱེད་པའི་དེབ་ཐེར་གསེར་གྱི་ལྡེ་མིག
  author: སྒ་ཀརྨ་དོན་གྲུབ་ཕུན་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.9379164983779095
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I01JW127:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW127
      total_pages: 725
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW127.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9379164983779095
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
